### PR TITLE
Added repeat method for recurring payment

### PR DESCRIPTION
**Pull request by amirulfirdaus**
Recreate another method for repeat transaction

### CODE REVIEW

**Comment by darylldoyle** [comment]
Thanks for the PR @amirulfirdaus, any chance you can add the class properties that you've added into `sagepay/src/AbstractSettings.php`?

I'll be happy to merge once those are in!

**Comment by amirulfirdaus** [comment]
Ah sorry forgotten to add them. I'll add it tonight. Thanks.

**Comment by amirulfirdaus** [comment]
Repeat class properties added. Anything I missed, let me know. Thanks.

**Comment by amirulfirdaus** [comment]
Hi @darylldoyle , any chance of merging the code to master? Or are there any code that I missed? Thanks.

**Comment by darylldoyle** [comment]
Thank you, merged!

**Pull request merged**
